apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios-server
data:
  port: "8001"
  db_host: mysql8:3306
  database: db-ms-docker-kube
#  username: root
#  password: sasa
  curso_url: ms-cursos-server:8002
  ms-usuarios-server.yaml: |-
    config:
      texto: configurando ambiente por defecto usuarios
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: config amb dev
    ---
    spring:
      config:
        activate:
          on-profile: pro
    config:
      texto: config amb pro
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-cursos-server
data:
  port: "8002"
  db_host: postgres14:5432
  database: db-ms-docker-kube
#  username: postgres
#  password: sasa
  usuario_url: ms-usuarios-server:8001




